package cdac.project.logigraph.vehicle.service;

import cdac.project.logigraph.order.entity.Order;
import cdac.project.logigraph.order.entity.OrderStatusHistory;
import cdac.project.logigraph.order.enums.OrderStatus;
import cdac.project.logigraph.order.repository.OrderRepository;
import cdac.project.logigraph.order.repository.OrderStatusHistoryRepository;
import cdac.project.logigraph.vehicle.entity.Vehicle;
import cdac.project.logigraph.vehicle.enums.VehicleStatus;
import cdac.project.logigraph.vehicle.repository.VehicleRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;

@Service
public class VehicleAssignmentService {

    private final VehicleRepository vehicleRepository;
    private final OrderRepository orderRepository;
    private final OrderStatusHistoryRepository statusHistoryRepository;

    public VehicleAssignmentService(
            VehicleRepository vehicleRepository,
            OrderRepository orderRepository,
            OrderStatusHistoryRepository statusHistoryRepository
    ) {
        this.vehicleRepository = vehicleRepository;
        this.orderRepository = orderRepository;
        this.statusHistoryRepository = statusHistoryRepository;
    }

    @Transactional
    public void assignVehicle(Integer orderId) {

        Order order = orderRepository.findById(orderId)
                .orElseThrow();

        if (order.getAssignedVehicleId() != null) {
            return;
        }

        Optional<Vehicle> vehicleOpt =
                vehicleRepository.findFirstIdleVehicleForUpdate();

        if (vehicleOpt.isEmpty()) {
            return;
        }

        Vehicle vehicle = vehicleOpt.get();
        vehicle.setStatus(VehicleStatus.ASSIGNED);
        vehicleRepository.save(vehicle);

        order.setAssignedVehicleId(vehicle.getId());
        order.setStatus(OrderStatus.ASSIGNED);
        orderRepository.save(order);

        // ✅ Timestamp is auto-generated by @PrePersist
        OrderStatusHistory history = new OrderStatusHistory();
        history.setOrderId(orderId);
        history.setStatus(OrderStatus.ASSIGNED);
        statusHistoryRepository.save(history);
    }
}
